/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_nnn1590_jnitest_MainActivity */

#ifndef _Included_org_nnn1590_jnitest_MainActivity
#define _Included_org_nnn1590_jnitest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef org_nnn1590_jnitest_MainActivity_DIALOG_DEBUG
#define org_nnn1590_jnitest_MainActivity_DIALOG_DEBUG 1L
#undef org_nnn1590_jnitest_MainActivity_DIALOG_FAILED_TO_LOAD_LIBRARY
#define org_nnn1590_jnitest_MainActivity_DIALOG_FAILED_TO_LOAD_LIBRARY 2L
/*
 * Class:     org_nnn1590_jnitest_MainActivity
 * Method:    addNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_nnn1590_jnitest_MainActivity_addNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_nnn1590_jnitest_MainActivity
 * Method:    addStaticNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_nnn1590_jnitest_MainActivity_addStaticNative
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_nnn1590_jnitest_MainActivity
 * Method:    addsNative
 * Signature: (I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_nnn1590_jnitest_MainActivity_addsNative
  (JNIEnv *, jclass, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
